# Generated by Django 5.1 on 2024-09-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessment", "0002_auto_20240921_1922"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="score",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
