# Generated by Django 5.1 on 2024-09-21 14:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assessment", "0003_alter_assessment_score"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assessment",
            name="user",
        ),
    ]
